// Animation 1 is always the idle animation and thus loops, even if the data says OneShot

root.Scene3D.Characters = {
    1: {
        Models: [237, 238],
        Animations: {
            1: { OneShot: true },
            2: { OneShot: true },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { OneShot: true },
            12: { OneShot: true },
            13: { OneShot: true },
            14: { OneShot: true }
        }
    },
    2: {
        Models: [239, 240, 241, 242, 243, 244, 245],
        Animations: {
            1: { LoopStart: 0, LoopEnd: 730 },
            2: { LoopStart: 60, LoopEnd: 270 },
            3: { LoopStart: 210, LoopEnd: 490 },
            4: { LoopStart: 85, LoopEnd: 335 },
            5: { LoopStart: 240, LoopEnd: 520 },
            6: { LoopStart: 150, LoopEnd: 430 },
            7: { LoopStart: 250, LoopEnd: 530 },
            8: { LoopStart: 190, LoopEnd: 470 },
            9: { LoopStart: 170, LoopEnd: 450 },
            10: { LoopStart: 95, LoopEnd: 525 },
            11: { LoopStart: 180, LoopEnd: 460 },
            12: { LoopStart: 210, LoopEnd: 490 },
            13: { LoopStart: 300, LoopEnd: 580 },
            14: { LoopStart: 260, LoopEnd: 540 },
            15: { LoopStart: 150, LoopEnd: 430 },
            16: { LoopStart: 90, LoopEnd: 220 },
            17: { OneShot: true },
            18: { LoopStart: 160, LoopEnd: 440 },
            19: { LoopStart: 130, LoopEnd: 410 },
            20: { LoopStart: 0, LoopEnd: 730 },
            21: { OneShot: true },
            22: { OneShot: true },
            23: { OneShot: true },
            24: { OneShot: true },
            25: { OneShot: true },
            26: { OneShot: true },
            27: { OneShot: true },
            28: { OneShot: true },
            29: { OneShot: true },
            30: { OneShot: true },
            31: { LoopStart: 210, LoopEnd: 490 },
            32: { LoopStart: 170, LoopEnd: 450 },
            33: { LoopStart: 0, LoopEnd: 570 },
            34: { LoopStart: 0, LoopEnd: 730 }
        }
    },
    3: {
        Models: [246, 247, 248, 249],
        Animations: {
            1: { LoopStart: 0, LoopEnd: 775 },
            2: { LoopStart: 169, LoopEnd: 595 },
            3: { LoopStart: 200, LoopEnd: 430 },
            4: { LoopStart: 143, LoopEnd: 463 },
            5: { LoopStart: 150, LoopEnd: 470 },
            6: { LoopStart: 205, LoopEnd: 525 },
            7: { LoopStart: 180, LoopEnd: 500 },
            8: { LoopStart: 190, LoopEnd: 500 },
            9: { LoopStart: 180, LoopEnd: 500 },
            10: { LoopStart: 175, LoopEnd: 495 },
            11: { LoopStart: 180, LoopEnd: 500 },
            12: { LoopStart: 185, LoopEnd: 505 },
            13: { LoopStart: 0, LoopEnd: 50 },
            14: { LoopStart: 165, LoopEnd: 485 },
            15: { LoopStart: 205, LoopEnd: 525 },
            16: { LoopStart: 150, LoopEnd: 240 },
            17: { OneShot: true },
            18: { LoopStart: 175, LoopEnd: 395 },
            19: { LoopStart: 180, LoopEnd: 420 },
            20: { LoopStart: 210, LoopEnd: 530 },
            21: { LoopStart: 0, LoopEnd: 730 },
            22: { OneShot: true },
            23: { LoopStart: 150, LoopEnd: 470 }
        }
    },
    4: {
        Models: [250, 251, 252, 253],
        Animations: {
            1: { LoopStart: 0, LoopEnd: 600 },
            2: { LoopStart: 175, LoopEnd: 455 },
            3: { LoopStart: 290, LoopEnd: 570 },
            4: { LoopStart: 290, LoopEnd: 570 },
            5: { LoopStart: 190, LoopEnd: 470 },
            6: { LoopStart: 400, LoopEnd: 700 },
            7: { LoopStart: 170, LoopEnd: 450 },
            8: { LoopStart: 225, LoopEnd: 505 },
            9: { LoopStart: 225, LoopEnd: 505 },
            10: { LoopStart: 185, LoopEnd: 485 },
            11: { LoopStart: 490, LoopEnd: 790 },
            12: { LoopStart: 0, LoopEnd: 600 },
            13: { LoopStart: 0, LoopEnd: 600 },
            14: { LoopStart: 180, LoopEnd: 460 }
        }
    },
    5: {
        Models: [254, 255],
        Animations: {
            1: { LoopStart: 0, LoopEnd: 690 },
            2: { LoopStart: 265, LoopEnd: 585 },
            3: { LoopStart: 210, LoopEnd: 530 },
            4: { LoopStart: 290, LoopEnd: 630 },
            5: { LoopStart: 280, LoopEnd: 360 },
            6: { LoopStart: 220, LoopEnd: 540 },
            7: { LoopStart: 120, LoopEnd: 440 },
            8: { LoopStart: 350, LoopEnd: 670 },
            9: { LoopStart: 220, LoopEnd: 540 },
            10: { LoopStart: 260, LoopEnd: 580 },
            11: { LoopStart: 400, LoopEnd: 700 },
            12: { LoopStart: 245, LoopEnd: 575 },
            13: { LoopStart: 205, LoopEnd: 525 },
            14: { LoopStart: 225, LoopEnd: 545 },
            15: { LoopStart: 315, LoopEnd: 635 },
            16: { LoopStart: 210, LoopEnd: 530 },
            17: { OneShot: true },
            18: { OneShot: true },
            19: { LoopStart: 0, LoopEnd: 320 },
            20: { OneShot: true },
            21: { LoopStart: 0, LoopEnd: 80 },
            22: { LoopStart: 0, LoopEnd: 80 },
            23: { LoopStart: 0, LoopEnd: 120 },
            24: { LoopStart: 0, LoopEnd: 80 },
            25: { LoopStart: 310, LoopEnd: 430 },
            26: { LoopStart: 210, LoopEnd: 330 },
            27: { OneShot: true },
            28: { LoopStart: 90, LoopEnd: 330 },
            29: { LoopStart: 15, LoopEnd: 260 },
            30: { LoopStart: 90, LoopEnd: 210 },
            31: { LoopStart: 0, LoopEnd: 80 }
        }
    },
    6: {
        Models: [256, 257, 258, 259, 260, 261],
        Animations: {
            1: { LoopStart: 90, LoopEnd: 705 },
            2: { LoopStart: 335, LoopEnd: 815 },
            3: { LoopStart: 240, LoopEnd: 720 },
            4: { LoopStart: 220, LoopEnd: 700 },
            5: { LoopStart: 220, LoopEnd: 700 },
            6: { LoopStart: 255, LoopEnd: 735 },
            7: { LoopStart: 310, LoopEnd: 790 },
            8: { LoopStart: 265, LoopEnd: 745 },
            9: { LoopStart: 260, LoopEnd: 740 },
            10: { LoopStart: 420, LoopEnd: 840 },
            11: { LoopStart: 370, LoopEnd: 790 },
            12: { LoopStart: 150, LoopEnd: 450 },
            13: { LoopStart: 240, LoopEnd: 720 },
            14: { LoopStart: 240, LoopEnd: 720 },
            15: { LoopStart: 255, LoopEnd: 735 },
            16: { OneShot: true },
            17: { OneShot: true },
            18: { OneShot: true }
        }
    },
    7: {
        Models: [262, 263, 264, 265],
        Animations: {
            1: { OneShot: true },
            2: { LoopStart: 280, LoopEnd: 640 },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true }
        }
    },
    8: {
        Models: [266, 267],
        Animations: {
            1: { LoopStart: 0, LoopEnd: 450 },
            2: { OneShot: true },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { LoopStart: 45, LoopEnd: 260 }
        }
    },
    9: {
        Models: [268, 269],
        Animations: {
            1: { OneShot: true },
            2: { LoopStart: 225, LoopEnd: 645 },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { LoopStart: 60, LoopEnd: 240 }
        }
    },
    10: {
        Models: [270, 271, 272],
        Animations: {
            1: { OneShot: true },
            2: { LoopStart: 175, LoopEnd: 455 },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { OneShot: true },
            12: { OneShot: true }
        }
    },
    11: {
        Models: [273],
        Animations: {
            1: { OneShot: true },
            2: { LoopStart: 260, LoopEnd: 720 },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { LoopStart: 40, LoopEnd: 220 }
        }
    },
    12: {
        Models: [274],
        Animations: {
            1: { LoopStart: 170, LoopEnd: 540 },
            2: { OneShot: true },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { LoopStart: 60, LoopEnd: 240 },
            12: { OneShot: true },
            13: { OneShot: true },
            14: { OneShot: true },
            15: { OneShot: true },
            16: { OneShot: true },
            17: { OneShot: true },
            18: { OneShot: true },
            19: { OneShot: true },
            20: { OneShot: true },
            21: { LoopStart: 170, LoopEnd: 540 },
            22: { LoopStart: 170, LoopEnd: 540 },
            23: { LoopStart: 170, LoopEnd: 540 },
            24: { LoopStart: 170, LoopEnd: 540 }
        }
    },
    13: {
        Models: [275],
        Animations: {
            1: { OneShot: true },
            2: { OneShot: true },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { LoopStart: 60, LoopEnd: 210 },
            12: { OneShot: true },
            13: { OneShot: true },
            14: { OneShot: true },
            15: { OneShot: true },
            16: { OneShot: true },
            17: { OneShot: true },
            18: { OneShot: true },
            19: { OneShot: true },
            20: { OneShot: true },
            21: { OneShot: true },
            22: { OneShot: true },
            23: { OneShot: true },
            24: { OneShot: true }
        }
    },
    14: {
        Models: [276],
        Animations: {
            1: { OneShot: true },
            2: { OneShot: true },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { OneShot: true }
        }
    },
    15: {
        Models: [277],
        Animations: {
            1: { OneShot: true },
            2: { OneShot: true },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { LoopStart: 80, LoopEnd: 264 }
        }
    },
    16: {
        Models: [278],
        Animations: {
            1: { OneShot: true },
            2: { OneShot: true },
            3: { OneShot: true },
            4: { OneShot: true },
            5: { OneShot: true },
            6: { OneShot: true },
            7: { OneShot: true },
            8: { OneShot: true },
            9: { OneShot: true },
            10: { OneShot: true },
            11: { OneShot: true }
        }
    },
    17: {
        Models: [279, 280, 281, 282],
        Animations: {
            1: { OneShot: true },
            2: { LoopStart: 215, LoopEnd: 535 },
            3: { LoopStart: 265, LoopEnd: 585 },
            4: { LoopStart: 300, LoopEnd: 620 },
            5: { LoopStart: 225, LoopEnd: 545 },
            6: { LoopStart: 180, LoopEnd: 500 },
            7: { LoopStart: 215, LoopEnd: 535 },
            8: { LoopStart: 280, LoopEnd: 600 },
            9: { LoopStart: 230, LoopEnd: 550 },
            10: { LoopStart: 330, LoopEnd: 650 },
            11: { LoopStart: 260, LoopEnd: 580 },
            12: { LoopStart: 270, LoopEnd: 590 },
            13: { LoopStart: 250, LoopEnd: 570 },
            14: { OneShot: true },
            15: { OneShot: true }
        }
    }
};