find_package(PkgConfig REQUIRED)

if(NOT TARGET WebP::webp)
    pkg_check_modules(_switch_webp REQUIRED IMPORTED_TARGET libwebp)
    add_library(WebP::webp INTERFACE IMPORTED)
    set_property(TARGET WebP::webp PROPERTY INTERFACE_LINK_LIBRARIES PkgConfig::_switch_webp)
endif()

if(NOT TARGET WebP::webpdecoder)
    pkg_check_modules(_switch_webpdecoder QUIET IMPORTED_TARGET libwebpdecoder)
    add_library(WebP::webpdecoder INTERFACE IMPORTED)
    if(TARGET PkgConfig::_switch_webpdecoder)
        set_property(TARGET WebP::webpdecoder PROPERTY INTERFACE_LINK_LIBRARIES PkgConfig::_switch_webpdecoder)
    else()
        set_property(TARGET WebP::webpdecoder PROPERTY INTERFACE_LINK_LIBRARIES WebP::webp)
    endif()
endif()

if(NOT TARGET WebP::webpdemux)
    pkg_check_modules(_switch_webpdemux QUIET IMPORTED_TARGET libwebpdemux)
    add_library(WebP::webpdemux INTERFACE IMPORTED)
    if(TARGET PkgConfig::_switch_webpdemux)
        set_property(TARGET WebP::webpdemux PROPERTY INTERFACE_LINK_LIBRARIES PkgConfig::_switch_webpdemux)
    else()
        set_property(TARGET WebP::webpdemux PROPERTY INTERFACE_LINK_LIBRARIES WebP::webp)
    endif()
endif()
