
root.PADcustomSizeA = 43;
root.PADcustomSizeB = 0;
root.PADcustomType = 0;
root.PADcustomA = {
  root.PADinput.PAD1UP,
  root.PADinput.PAD1DOWN,
  root.PADinput.PAD1LEFT,
  root.PADinput.PAD1RIGHT,
  root.PADinput.PAD1A | root.PADinput.PAD1START,
  root.PADinput.PAD1A,
  root.PADinput.PAD1B,
  root.PADinput.PAD1L1,
  root.PADinput.PAD1R1,
  root.PADinput.PAD1X,
  root.PADinput.PAD1START,
  0,
  root.PADinput.PAD1Y,
  root.PADinput.PAD1R3,
  root.PADinput.PAD1A | root.PADinput.PAD1B,
  root.PADinput.PAD1A,
  root.PADinput.PAD1B,
  root.PADinput.PAD1X,
  root.PADinput.PAD1Y,
  0,
  0,
  root.PADinput.PAD1SELECT,
  0,
  root.PADinput.PAD1A,
  0,
  0,
  0,
  0,
  root.PADinput.PAD1UP_LS | root.PADinput.PAD1UP_DIRECT,
  root.PADinput.PAD1DOWN_LS | root.PADinput.PAD1DOWN_DIRECT,
  root.PADinput.PAD1LEFT_LS | root.PADinput.PAD1LEFT_DIRECT,
  root.PADinput.PAD1RIGHT_LS | root.PADinput.PAD1RIGHT_DIRECT,
  root.PADinput.PAD1UP_RS,
  root.PADinput.PAD1DOWN_RS,
  root.PADinput.PAD1LEFT_RS,
  root.PADinput.PAD1RIGHT_RS,
  root.PADinput.PAD1L2,
  root.PADinput.PAD1R2,
  root.PADinput.PAD1LEFT | root.PADinput.PAD1L2,
  root.PADinput.PAD1RIGHT | root.PADinput.PAD1R2,
  0xF1000,
  root.PADinput.PAD1L1,
  root.PADinput.PAD1R1,
}